# Generated by Django 5.0 on 2024-09-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPluginModel',
        ),
    ]
