# Generated by Django 5.0 on 2024-09-13 08:18

import djangocms_text_ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(),
        ),
    ]
