# Generated by Django 5.0 on 2024-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_blogpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
