# Generated by Django 5.0 on 2024-09-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_scheduledtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archival Date'),
        ),
    ]
