# Generated by Django 5.0 on 2024-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posttranslation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='content',
            field=models.TextField(),
        ),
    ]
